export const UR5E_ROBOT_DATA = {
  "robot-agent": {
    type: "robotAgentType",
    id: "robot-agent",
    name: "UR5e Robot Agent",
    canDelete: true,
    canEdit: true,
    properties: {
      description:
        "A robot created by Universal Robots. This robot has a payload of 5kg.",
      initialJointState: {
        elbow_joint: -1.57,
        shoulder_lift_joint: -0.55,
        shoulder_pan_joint: 1.57,
        wrist_1_joint: -2.13,
        wrist_2_joint: 1.6,
        wrist_3_joint: -0.2,
      },
      jointLinkMap: [],
      pinchPointPairLinks: [
        {
          link1: "base_link",
          link2: "forearm_link",
        },
        {
          link1: "base_link",
          link2: "gripper",
        },
        {
          link1: "base_link",
          link2: "upper_arm_link",
        },
        {
          link1: "base_link",
          link2: "wrist_1_link",
        },
        {
          link1: "base_link",
          link2: "wrist_2_link",
        },
        {
          link1: "base_link",
          link2: "wrist_3_link",
        },
        {
          link1: "shoulder_link",
          link2: "forearm_link",
        },
        {
          link1: "shoulder_link",
          link2: "gripper",
        },
        {
          link1: "shoulder_link",
          link2: "wrist_1_link",
        },
        {
          link1: "shoulder_link",
          link2: "wrist_2_link",
        },
        {
          link1: "shoulder_link",
          link2: "wrist_3_link",
        },
        {
          link1: "upper_arm_link",
          link2: "gripper",
        },
        {
          link1: "upper_arm_link",
          link2: "wrist_1_link",
        },
        {
          link1: "upper_arm_link",
          link2: "wrist_2_link",
        },
        {
          link1: "upper_arm_link",
          link2: "wrist_3_link",
        },
        {
          link1: "forearm_link",
          link2: "gripper",
        },
        {
          link1: "forearm_link",
          link2: "wrist_2_link",
        },
        {
          link1: "forearm_link",
          link2: "wrist_3_link",
        },
        {
          link1: "wrist_1_link",
          link2: "wrist_2_link",
        },
      ],
      urdf: `<?xml version="1.0" ?>
      <!-- =================================================================================== -->
      <!-- |    This document was autogenerated by xacro from src/universal_robot/ur_description/urdf/ur5.xacro | -->
      <!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
      <!-- =================================================================================== -->
      <robot name="ur5_robot">
        <!--
          Base UR robot series xacro macro.
      
          NOTE: this is NOT a URDF. It cannot directly be loaded by consumers
          expecting a flattened '.urdf' file. See the top-level '.xacro' for that
          (but note: that .xacro must still be processed by the xacro command).
      
          For use in '.launch' files: use one of the 'load_urX.launch' convenience
          launch files.
      
          This file models the base kinematic chain of a UR robot, which then gets
          parameterised by various configuration files to convert it into a UR3(e),
          UR5(e), UR10(e) or UR16e.
      
          NOTE: the default kinematic parameters (ie: link lengths, frame locations,
          offets, etc) do not correspond to any particular robot. They are defaults
          only. There WILL be non-zero offsets between the Forward Kinematics results
          in TF (ie: robot_state_publisher) and the values reported by the Teach
          Pendant.
      
          For accurate (and robot-specific) transforms, the 'kinematics_parameters_file'
          parameter MUST point to a .yaml file containing the appropriate values for
          the targetted robot.
      
          If using the UniversalRobots/Universal_Robots_ROS_Driver, follow the steps
          described in the readme of that repository to extract the kinematic
          calibration from the controller and generate the required .yaml file.
      
          Main author of the migration to yaml configs: Ludovic Delval.
      
          Contributors to previous versions (in no particular order):
      
           - Felix Messmer
           - Kelsey Hawkins
           - Wim Meeussen
           - Shaun Edwards
           - Nadia Hammoudeh Garcia
           - Dave Hershberger
           - G. vd. Hoorn
           - Philip Long
           - Dave Coleman
           - Miguel Prada
           - Mathias Luedtke
           - Marcel Schnirring
           - Felix von Drigalski
           - Felix Exner
           - Jimmy Da Silva
           - Ajit Krisshna N L
           - Muhammad Asif Rana
        -->
        <!--
          NOTE: the macro defined in this file is NOT part of the public API of this
                package. Users CANNOT rely on this file being available, or stored in
                this location. Nor can they rely on the existence of the macro.
        -->
        <!-- links: main serial chain -->
        <link name="base_link">
          <visual>
            <geometry>
              <mesh filename="package://ur_description/meshes/ur5/visual/base.dae"/>
            </geometry>
            <material name="LightGrey">
              <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
          </visual>
          <collision>
            <origin rpy="0 0 3.141592653589793" xyz="0 0 0.046"/>
            <geometry>
              <cylinder length="0.09" radius="0.08"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="4.0"/>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
            <inertia ixx="0.00443333156" ixy="0.0" ixz="0.0" iyy="0.00443333156" iyz="0.0" izz="0.0072"/>
          </inertial>
        </link>
        <link name="shoulder_link">
          <visual>
            <geometry>
              <mesh filename="package://ur_description/meshes/ur5/visual/shoulder.dae"/>
            </geometry>
            <material name="LightGrey">
              <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
          </visual>
          <collision>
            <origin rpy="0 0 3.141592653589793" xyz="0 0 0"/>
            <geometry>
              <cylinder length="0.135" radius="0.065"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="3.7"/>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
            <inertia ixx="0.010267495893" ixy="0.0" ixz="0.0" iyy="0.010267495893" iyz="0.0" izz="0.00666"/>
          </inertial>
        </link>
        <link name="upper_arm_link">
          <visual>
            <geometry>
              <mesh filename="package://ur_description/meshes/ur5/visual/upperarm.dae"/>
            </geometry>
            <material name="LightGrey">
              <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
          </visual>
          <collision>
            <origin rpy="1.5707963267948966 -1.5707963267948966 0" xyz="0 0 0"/>
            <geometry>
              <cylinder length="0.135" radius="0.06"/>
            </geometry>
          </collision>
          <collision>
            <origin rpy="0 0 -1.5707963267948966" xyz="0 0 0.21"/>
            <geometry>
              <cylinder length="0.3" radius="0.06"/>
            </geometry>
          </collision>
          <collision>
            <origin rpy="1.5707963267948966 -1.5707963267948966 0" xyz="0 0 0.43"/>
            <geometry>
              <cylinder length="0.135" radius="0.06"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="8.393"/>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.2125"/>
            <inertia ixx="0.133885781862" ixy="0.0" ixz="0.0" iyy="0.133885781862" iyz="0.0" izz="0.0151074"/>
          </inertial>
        </link>
        <link name="forearm_link">
          <visual>
            <geometry>
              <mesh filename="package://ur_description/meshes/ur5/visual/forearm.dae"/>
            </geometry>
            <material name="LightGrey">
              <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
          </visual>
          <collision>
            <origin rpy="1.5707963267948966 -1.5707963267948966 0" xyz="0 0 0"/>
            <geometry>
              <cylinder length="0.11" radius="0.06"/>
            </geometry>
          </collision>
          <collision>
            <origin rpy="0 0 -1.5707963267948966" xyz="0 0 0.2"/>
            <geometry>
              <cylinder length="0.28" radius="0.05"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="2.275"/>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.196"/>
            <inertia ixx="0.0311796208615" ixy="0.0" ixz="0.0" iyy="0.0311796208615" iyz="0.0" izz="0.004095"/>
          </inertial>
        </link>
        <link name="wrist_1_link">
          <visual>
            <!-- TODO: Move this to a parameter -->
            <geometry>
              <mesh filename="package://ur_description/meshes/ur5/visual/wrist1.dae"/>
            </geometry>
            <material name="LightGrey">
              <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
          </visual>
          <collision>
            <origin rpy="1.5707963267948966 -1.5707963267948966 0" xyz="0 0.01 0"/>
            <geometry>
              <cylinder length="0.14" radius="0.042"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="1.219"/>
            <origin rpy="0 0 0" xyz="0.0 0.127 0.0"/>
            <inertia ixx="0.00255989897604" ixy="0.0" ixz="0.0" iyy="0.00255989897604" iyz="0.0" izz="0.0021942"/>
          </inertial>
        </link>
        <link name="wrist_2_link">
          <visual>
            <geometry>
              <mesh filename="package://ur_description/meshes/ur5/visual/wrist2.dae"/>
            </geometry>
            <material name="LightGrey">
              <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
          </visual>
          <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
              <cylinder length="0.11" radius="0.04"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="1.219"/>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.1"/>
            <inertia ixx="0.00255989897604" ixy="0.0" ixz="0.0" iyy="0.00255989897604" iyz="0.0" izz="0.0021942"/>
          </inertial>
        </link>
        <link name="wrist_3_link">
          <visual>
            <geometry>
              <mesh filename="package://ur_description/meshes/ur5/visual/wrist3.dae"/>
            </geometry>
            <material name="LightGrey">
              <color rgba="0.7 0.7 0.7 1.0"/>
            </material>
          </visual>
          <collision>
            <origin rpy="1.5707963267948966 -1.5707963267948966 0" xyz="0 0.02 0"/>
            <geometry>
              <cylinder length="0.16" radius="0.04"/>
            </geometry>
          </collision>
          <inertial>
            <mass value="0.1879"/>
            <origin rpy="1.57079632679 0 0" xyz="0.0 0.0771 0.0"/>
            <inertia ixx="9.89041005217e-05" ixy="0.0" ixz="0.0" iyy="9.89041005217e-05" iyz="0.0" izz="0.0001321171875"/>
          </inertial>
        </link>
        <!-- joints: main serial chain -->
        <joint name="shoulder_pan_joint" type="revolute">
          <parent link="base_link"/>
          <child link="shoulder_link"/>
          <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.163"/>
          <axis xyz="0 0 1"/>
          <limit effort="150.0" lower="-6.28318530718" upper="6.28318530718" velocity="3.14"/>
          <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <joint name="shoulder_lift_joint" type="revolute">
          <parent link="shoulder_link"/>
          <child link="upper_arm_link"/>
          <origin rpy="0.0 1.57079632679 0.0" xyz="0.0 0.138 0.0"/>
          <axis xyz="0 1 0"/>
          <limit effort="150.0" lower="-6.28318530718" upper="6.28318530718" velocity="3.14"/>
          <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <joint name="elbow_joint" type="revolute">
          <parent link="upper_arm_link"/>
          <child link="forearm_link"/>
          <origin rpy="0.0 0.0 0.0" xyz="0.0 -0.131 0.425"/>
          <axis xyz="0 1 0"/>
          <limit effort="150.0" lower="-3.14159265359" upper="3.14159265359" velocity="3.14"/>
          <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <joint name="wrist_1_joint" type="revolute">
          <parent link="forearm_link"/>
          <child link="wrist_1_link"/>
          <origin rpy="0.0 1.57079632679 0.0" xyz="0.0 0.0 0.392"/>
          <axis xyz="0 1 0"/>
          <limit effort="28.0" lower="-6.28318530718" upper="6.28318530718" velocity="6.28"/>
          <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <joint name="wrist_2_joint" type="revolute">
          <parent link="wrist_1_link"/>
          <child link="wrist_2_link"/>
          <origin rpy="0.0 0.0 0.0" xyz="0.0 0.127 0.0"/>
          <axis xyz="0 0 1"/>
          <limit effort="28.0" lower="-6.28318530718" upper="6.28318530718" velocity="6.28"/>
          <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <joint name="wrist_3_joint" type="revolute">
          <parent link="wrist_2_link"/>
          <child link="wrist_3_link"/>
          <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.1"/>
          <axis xyz="0 1 0"/>
          <limit effort="28.0" lower="-6.28318530718" upper="6.28318530718" velocity="6.28"/>
          <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <!-- ROS-Industrial 'flange' frame: attachment point for EEF models -->
        <link name="flange"/>
        <joint name="wrist_3-flange" type="fixed">
          <parent link="wrist_3_link"/>
          <child link="flange"/>
          <origin rpy="0 -3.14 -1.5707963267948966" xyz="0 0.09 0"/>
        </joint>
        <!-- ROS-Industrial 'tool0' frame: all-zeros tool frame -->
        <link name="tool0"/>
        <joint name="flange-tool0" type="fixed">
          <!-- default toolframe: X+ left, Y+ up, Z+ front -->
          <origin rpy="1.5707963267948966 0 1.5707963267948966" xyz="0 0 0"/>
          <parent link="flange"/>
          <child link="tool0"/>
        </joint>
      </robot>`,
      compileFn: 10,
      updateFields: [
        "initialJointState",
        "position",
        "rotation",
        "relativeTo",
        "urdf",
      ],
      position: {
        x: 0,
        y: 0,
        z: 0.38,
      },
      rotation: {
        w: 1,
        x: 0,
        y: 0,
        z: 0,
      },
      relativeTo: "pedestal",
      status: "VALID",
      compiled: {},
      singleton: true,
      jointLimit: {
        elbow_joint: {
          lower: -3.141592653589793,
          upper: 3.141592653589793,
        },
        shoulder_lift_joint: {
          lower: -6.283185307179586,
          upper: 6.283185307179586,
        },
        shoulder_pan_joint: {
          lower: -6.283185307179586,
          upper: 6.283185307179586,
        },
        wrist_1_joint: {
          lower: -6.283185307179586,
          upper: 6.283185307179586,
        },
        wrist_2_joint: {
          lower: -6.283185307179586,
          upper: 6.283185307179586,
        },
        wrist_3_joint: {
          lower: -3.141592653589793,
          upper: 3.141592653589793,
        },
      },
    },
    dataType: "INSTANCE",
    selected: false,
    editing: false,
  },
  base_link: {
    id: "base_link",
    name: "Robot Base",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0,
        y: 0,
        z: 0,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: "robotBaseMesh",
      collision: "robotBaseCollision",
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  shoulder_link: {
    id: "shoulder_link",
    name: "Shoulder Link",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0,
        y: 0,
        z: 0.1519,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 0.706825181105366,
        w: 0.7073882691671998,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: "robotShoulderLinkMesh",
      collision: "robotShoulderCollision",
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0,
              y: 0,
              z: 0.1519,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0.706825181105366,
              w: 0.7073882691671998,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  upper_arm_link: {
    id: "upper_arm_link",
    name: "Upper Arm Link",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0,
        y: 0,
        z: 0.1519,
      },
      rotation: {
        x: 0.34568476425181466,
        y: 0.6168484772346602,
        z: 0.3451934416564831,
        w: 0.6171235595363384,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: "robotUpperArmLinkMesh",
      collision: "robotUpperArmLinkCollision",
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0,
              y: 0,
              z: 0.1519,
            },
            rotation: {
              x: 0.34568476425181466,
              y: 0.6168484772346602,
              z: 0.3451934416564831,
              w: 0.6171235595363384,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  forearm_link: {
    id: "forearm_link",
    name: "Forearm Link",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: -0.00016541104688952424,
        y: -0.2077175339391811,
        z: 0.2792527433289551,
      },
      rotation: {
        x: -0.19147068957439534,
        y: 0.6806900727471037,
        z: -0.19201268051241213,
        w: 0.6805373835579399,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: "robotForearmLinkMesh",
      collision: "robotForearmLinkCollision",
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: -0.00016541104688952424,
              y: -0.2077175339391811,
              z: 0.2792527433289551,
            },
            rotation: {
              x: -0.19147068957439534,
              y: 0.6806900727471037,
              z: -0.19201268051241213,
              w: 0.6805373835579399,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
    },
  },
  wrist_1_link: {
    id: "wrist_1_link",
    name: "Wrist 1 Link",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0.1122731990583812,
        y: -0.09648879318889156,
        z: 0.4611423009970626,
      },
      rotation: {
        x: 0.6882284946623838,
        y: -0.16230076782720684,
        z: 0.6883575207424465,
        w: -0.16175266160023669,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: "robotWrist1LinkMesh",
      collision: "robotWrist1Collision",
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0.1122731990583812,
              y: -0.09648879318889156,
              z: 0.4611423009970626,
            },
            rotation: {
              x: 0.6882284946623838,
              y: -0.16230076782720684,
              z: 0.6883575207424465,
              w: -0.16175266160023669,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  wrist_2_link: {
    id: "wrist_2_link",
    name: "Wrist 2 Link",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0.11233402832926202,
        y: -0.02010147568406853,
        z: 0.4992158682612048,
      },
      rotation: {
        x: -0.5262071308517355,
        y: 0.007893698999081546,
        z: 0.012077258426380468,
        w: 0.8502340176597257,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: "robotWrist2LinkMesh",
      collision: "robotWrist2Collision",
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0.11233402832926202,
              y: -0.02010147568406853,
              z: 0.4992158682612048,
            },
            rotation: {
              x: -0.5262071308517355,
              y: 0.007893698999081546,
              z: 0.012077258426380468,
              w: 0.8502340176597257,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  wrist_3_link: {
    id: "wrist_3_link",
    name: "Wrist 3 Link",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0.10997166924094973,
        y: 0.016419404286072192,
        z: 0.4259474945536873,
      },
      rotation: {
        x: 0.968133140183572,
        y: 0.10011039739487268,
        z: 0.008822942793695915,
        w: -0.2293867626786602,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: "robotWrist3LinkMesh",
      collision: "robotWrist3Collision",
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0.10997166924094973,
              y: 0.016419404286072192,
              z: 0.4259474945536873,
            },
            rotation: {
              x: 0.968133140183572,
              y: 0.10011039739487268,
              z: 0.008822942793695915,
              w: -0.2293867626786602,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  flange: {
    id: "flange",
    name: "Flange",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0.10997166924094973,
        y: 0.016419404286072192,
        z: 0.4259474945536873,
      },
      rotation: {
        x: 0.5531162241305279,
        y: 0.6444036787317046,
        z: -0.3149065186581716,
        w: 0.42383985884674,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: null,
      collision: null,
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0.10997166924094973,
              y: 0.016419404286072192,
              z: 0.4259474945536873,
            },
            rotation: {
              x: 0.5531162241305279,
              y: 0.6444036787317046,
              z: -0.3149065186581716,
              w: 0.42383985884674,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  tool0: {
    id: "tool0",
    name: "Tool Hookup",
    type: "linkType",
    dataType: "INSTANCE",
    canDelete: false,
    canEdit: true,
    selected: false,
    editing: false,
    properties: {
      agent: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent"],
      description: "",
      position: {
        x: 0.10997166924094973,
        y: 0.016419404286072192,
        z: 0.4259474945536873,
      },
      rotation: {
        x: 0.968133140183572,
        y: 0.1001103973948726,
        z: 0.008822942793695693,
        w: -0.2293867626786602,
      },
      relativeTo: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      mesh: null,
      collision: null,
      status: "VALID",
      compiled: {
        "{}": {
          status: "VALID",
          otherPropertyUpdates: {
            frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
            position: {
              x: 0.10997166924094973,
              y: 0.016419404286072192,
              z: 0.4259474945536873,
            },
            rotation: {
              x: 0.968133140183572,
              y: 0.1001103973948726,
              z: 0.008822942793695693,
              w: -0.2293867626786602,
            },
            scale: {
              x: 1,
              y: 1,
              z: 1,
            },
          },
        },
      },
      singleton: true,
      frame: "robot-agent-988926121c1911eccbe2600155d1a70a2",
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
    },
  },
  robotBaseMesh: {
    type: "meshType",
    id: "robotBaseMesh",
    name: "Robot Base Mesh",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 1,
        w: 0,
      },
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      keyword: "package://ur_description/meshes/ur3/visual/base.dae",
      extraParams: null,
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      updateFields: ["position", "rotation", "scale"],
      singleton: true,
    },
  },
  robotShoulderLinkMesh: {
    type: "meshType",
    id: "robotShoulderLinkMesh",
    name: "Robot Shoulder Link Mesh",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 1,
        w: 0,
      },
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      keyword: "package://ur_description/meshes/ur3/visual/shoulder.dae",
      extraParams: null,
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      updateFields: ["position", "rotation", "scale"],
      singleton: true,
    },
  },
  robotUpperArmLinkMesh: {
    type: "meshType",
    id: "robotUpperArmLinkMesh",
    name: "Robot Upper Arm Link Mesh",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0.12,
      },
      rotation: {
        x: 0.5,
        y: -0.5,
        z: -0.5,
        w: 0.5,
      },
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      keyword: "package://ur_description/meshes/ur3/visual/upperarm.dae",
      extraParams: null,
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      updateFields: ["position", "rotation", "scale"],
      singleton: true,
    },
  },
  robotForearmLinkMesh: {
    type: "meshType",
    id: "robotForearmLinkMesh",
    name: "Robot Forearm Link Mesh",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0.027,
      },
      rotation: {
        x: 0.5,
        y: -0.5,
        z: -0.5,
        w: 0.5,
      },
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      keyword: "package://ur_description/meshes/ur3/visual/forearm.dae",
      extraParams: null,
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      updateFields: ["position", "rotation", "scale"],
      singleton: true,
    },
  },
  robotWrist1LinkMesh: {
    type: "meshType",
    id: "robotWrist1LinkMesh",
    name: "Robot Wrist 1 Link Mesh",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: -0.104,
      },
      rotation: {
        x: 0.7071068,
        y: 0,
        z: 0,
        w: 0.7071068,
      },
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      keyword: "package://ur_description/meshes/ur3/visual/wrist1.dae",
      extraParams: null,
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      updateFields: ["position", "rotation", "scale"],
      singleton: true,
    },
  },
  robotWrist2LinkMesh: {
    type: "meshType",
    id: "robotWrist2LinkMesh",
    name: "Robot Wrist 2 Link Mesh",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: -0.08535,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1,
      },
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      keyword: "package://ur_description/meshes/ur3/visual/wrist2.dae",
      extraParams: null,
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      updateFields: ["position", "rotation", "scale"],
      singleton: true,
    },
  },
  robotWrist3LinkMesh: {
    type: "meshType",
    id: "robotWrist3LinkMesh",
    name: "Robot Wrist 3 Link Mesh",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: -0.0921,
      },
      rotation: {
        x: 0.7071068,
        y: 0,
        z: 0,
        w: 0.7071068,
      },
      scale: {
        x: 1,
        y: 1,
        z: 1,
      },
      keyword: "package://ur_description/meshes/ur3/visual/wrist3.dae",
      extraParams: null,
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      updateFields: ["position", "rotation", "scale"],
      singleton: true,
    },
  },
  robotUpperArmLinkCollision: {
    type: "collisionBodyType",
    id: "robotUpperArmLinkCollision",
    name: "Robot Upper Arm Collision Body",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      componentShapes: [
        "robotUpperArmCollisionShape0",
        "robotUpperArmCollisionShape1",
        "robotUpperArmCollisionShape2",
      ],
      updateFields: ["componentShapes"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotUpperArmCollisionShape0: {
    type: "collisionShapeType",
    id: "robotUpperArmCollisionShape0",
    name: "Robot Upper Arm Link Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: -0.127,
        y: 0,
        z: 0.12,
      },
      rotation: {
        x: 0.5,
        y: -0.5,
        z: -0.5,
        w: 0.5,
      },
      scale: {
        x: 0.1,
        y: 0.1,
        z: 0.145,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotUpperArmCollisionShape1: {
    type: "collisionShapeType",
    id: "robotUpperArmCollisionShape1",
    name: "Robot Upper Arm Link Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0.125,
      },
      rotation: {
        x: 0,
        y: 0,
        z: -0.7071067811865475,
        w: 0.7071067811865476,
      },
      scale: {
        x: 0.1,
        y: 0.1,
        z: 0.11,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotUpperArmCollisionShape2: {
    type: "collisionShapeType",
    id: "robotUpperArmCollisionShape2",
    name: "Robot Upper Arm Link Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: -0.245,
        y: 0,
        z: 0.125,
      },
      rotation: {
        x: 0,
        y: 0,
        z: -0.7071067811865475,
        w: 0.7071067811865476,
      },
      scale: {
        x: 0.08,
        y: 0.08,
        z: 0.11,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotForearmLinkCollision: {
    type: "collisionBodyType",
    id: "robotForearmLinkCollision",
    name: "Robot Forearm Collision Body",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      componentShapes: [
        "robotForearmCollisionShape0",
        "robotForearmCollisionShape1",
      ],
      updateFields: ["componentShapes"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotForearmCollisionShape0: {
    type: "collisionShapeType",
    id: "robotForearmCollisionShape0",
    name: "Robot Forearm Link Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: -0.07,
        y: 0,
        z: 0.027,
      },
      rotation: {
        x: 0.5,
        y: -0.5,
        z: -0.5,
        w: 0.5,
      },
      scale: {
        x: 0.08,
        y: 0.08,
        z: 0.2,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotForearmCollisionShape1: {
    type: "collisionShapeType",
    id: "robotForearmCollisionShape1",
    name: "Robot Forearm Link Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: -0.215,
        y: 0,
        z: 0.027,
      },
      rotation: {
        x: 0,
        y: 0,
        z: -0.7071067811865475,
        w: 0.7071067811865476,
      },
      scale: {
        x: 0.08,
        y: 0.08,
        z: 0.095,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotWrist1Collision: {
    type: "collisionBodyType",
    id: "robotWrist1Collision",
    name: "Robot Wrist 1 Collision Body",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      componentShapes: ["robotWrist1CollisionShape0"],
      updateFields: ["componentShapes"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotWrist1CollisionShape0: {
    type: "collisionShapeType",
    id: "robotWrist1CollisionShape0",
    name: "Robot Wrist 1 Collision Shape 0",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0,
      },
      rotation: {
        x: 0.7071067811865475,
        y: 0,
        z: 0,
        w: 0.7071067811865476,
      },
      scale: {
        x: 0.07,
        y: 0.07,
        z: 0.095,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotWrist2Collision: {
    type: "collisionBodyType",
    id: "robotWrist2Collision",
    name: "Robot Wrist 2 Collision Body",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      componentShapes: ["robotWrist2CollisionShape0"],
      updateFields: ["componentShapes"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotWrist2CollisionShape0: {
    type: "collisionShapeType",
    id: "robotWrist2CollisionShape0",
    name: "Robot Wrist 2 Collision Shape 0",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: -0.008,
        z: 0.01,
      },
      rotation: {
        x: 0.7071067811865475,
        y: 0,
        z: 0,
        w: 0.7071067811865476,
      },
      scale: {
        x: 0.08,
        y: 0.08,
        z: 0.1,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotWrist3Collision: {
    type: "collisionBodyType",
    id: "robotWrist3Collision",
    name: "Robot Wrist 3 Collision Body",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      componentShapes: ["robotWrist3CollisionShape0"],
      updateFields: ["componentShapes"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotWrist3CollisionShape0: {
    type: "collisionShapeType",
    id: "robotWrist3CollisionShape0",
    name: "Robot Wrist 3 Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: -0.01,
        z: -0.015,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 0,
        w: 1,
      },
      scale: {
        x: 0.08,
        y: 0.08,
        z: 0.04,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotShoulderCollision: {
    type: "collisionBodyType",
    id: "robotShoulderCollision",
    name: "Robot Shoulder Collision Body",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      componentShapes: ["robotShoulderCollisionShape0"],
      updateFields: ["componentShapes"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotShoulderCollisionShape0: {
    type: "collisionShapeType",
    id: "robotShoulderCollisionShape0",
    name: "Robot Shoulder Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 1,
        w: 0,
      },
      scale: {
        x: 0.13,
        y: 0.13,
        z: 0.11,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotBaseCollision: {
    type: "collisionBodyType",
    id: "robotBaseCollision",
    name: "Robot Base Collision Body",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      componentShapes: ["robotBaseCollisionShape0"],
      updateFields: ["componentShapes"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
  robotBaseCollisionShape0: {
    type: "collisionShapeType",
    id: "robotBaseCollisionShape0",
    name: "Robot Base Collision Shape",
    canDelete: true,
    canEdit: true,
    dataType: "INSTANCE",
    selected: false,
    editing: false,
    properties: {
      position: {
        x: 0,
        y: 0,
        z: 0.04,
      },
      rotation: {
        x: 0,
        y: 0,
        z: 1,
        w: 0,
      },
      scale: {
        x: 0.13,
        y: 0.13,
        z: 0.09,
      },
      keyword: "cylinder",
      radius: 0,
      length: 0,
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      status: "PENDING",
      compileFn: 0,
      compiled: {},
      singleton: true,
    },
  },
};
