export const PANDA_GRIPPER_DATA = {
  "gripper-panda": {
    type: "gripperType",
    id: "gripper-panda",
    name: "Panda Gripper",
    canDelete: true,
    canEdit: true,
    properties: {
      description:
        "The gripper of the robot. This specific model is a standard part of the Panda robot.",
      initialGripState: 30,
      gripperIndex: [70, 61.25, 52.5, 43.75, 35, 26.25, 17.5, 8.75, 0],
      gripperFrames: {
        panda_hand: [
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "gripper-panda",
            position: {
              x: 0,
              y: 0,
              z: 0,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
        ],
        panda_leftfinger: [
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.04,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.035,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.03,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.025,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.02,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.015,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.01,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0.005,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
        ],
        panda_rightfinger: [
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.04,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.035,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.03,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.025,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.02,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.015,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.01,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: -0.005,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
          {
            frame: "panda_hand",
            position: {
              x: 0,
              y: 0,
              z: 0.0584,
            },
            rotation: {
              x: 0,
              y: 0,
              z: 0,
              w: 1,
            },
          },
        ],
      },
      compileFn: 12,
      updateFields: [
        "initialGripState",
        "position",
        "rotation",
        "relativeTo",
        "gripperIndex",
        "gripperFrames",
        "gripOffset",
      ],
      position: {
        x: 0,
        y: 0,
        z: 0,
      },
      rotation: {
        w: 1,
        x: 0,
        y: 0,
        z: 0,
      },
      relativeTo: "panda_connector",
      status: "PENDING",
      compiled: {},
      singleton: true,
      gripPositionOffset: {
        x: 0,
        y: 0,
        z: 0.10,
      },
      gripRotationOffset: {
        w: 0,//0.5,
        x: 0.707,//0.5,
        y: 0,//-0.5,
        z: 0.707,//0.5,
      },
    },
    dataType: "INSTANCE",
    selected: false,
    editing: false,
  },
  "collisionShapeType-590b0e9d-5cd2-4bdd-a457-8abc047c9a98": {
    id: "collisionShapeType-590b0e9d-5cd2-4bdd-a457-8abc047c9a98",
    type: "collisionShapeType",
    dataType: "INSTANCE",
    properties: {
      position: { x: 0, y: 0, z: 0.03 },
      rotation: { w: 1, x: 0, y: 0, z: 0 },
      scale: { x: 0.04, y: 0.2, z: 0.08 },
      keyword: "cube",
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      compileFn: 0,
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_hand-cube-0",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  "meshType-a0dd44b0-02d0-4c47-a14a-d3e6d2535d09": {
    id: "meshType-a0dd44b0-02d0-4c47-a14a-d3e6d2535d09",
    type: "meshType",
    dataType: "INSTANCE",
    properties: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { w: 1, x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      keyword: "package://franka_ros/franka_description/meshes/visual/hand.dae",
      extraParams: null,
      compileFn: 0,
      updateFields: ["position", "rotation", "scale"],
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_hand-mesh",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  panda_hand: {
    id: "panda_hand",
    type: "linkType",
    dataType: "INSTANCE",
    properties: {
      agent: "robotAgentType-3291d50f-9b47-4c7d-befb-dbc7a7311471",
      frameKey: "panda_hand",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent", "frameKey"],
      position: { x: 0, y: 0, z: 0 },
      rotation: {
        w: 1,//0.9238795325112867,
        x: 0,
        y: 0,
        z: 0//-0.3826834323650898,
      },
      relativeTo: "panda_connector",
      mesh: "meshType-a0dd44b0-02d0-4c47-a14a-d3e6d2535d09",
      collision: "collisionBodyType-86896e24-85dd-44b3-8e34-b42b3b35978c",
      singleton: false,
      status: "PENDING",
      compiled: {
        "{}": {
          status: "PENDING",
          otherPropertyUpdates: {
            frame: "panda_connector",
            position: { x: 0, y: 0, z: 0 },
            rotation: {
              w: 1, //0.9238795325112867,
              x: 0,
              y: 0,
              z: 0, //-0.3826834323650898,
            },
            scale: { x: 1, y: 1, z: 1 },
          },
        },
      },
      frame: "panda_connector",
      scale: { x: 1, y: 1, z: 1 },
    },
    name: "panda_hand",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
    raw: {
      visual: [
        {
          geometry: {
            mesh: {
              filename:
                "package://franka_ros/franka_description/meshes/visual/hand.dae",
            },
          },
        },
      ],
      collision: [
        {
          origin: { rpy: "0 0 0", xyz: "0.0 0.0 0.03" },
          geometry: { box: { size: "0.04 0.2 0.08" } },
        },
      ],
      inertial: {
        origin: { rpy: "0 0 0", xyz: "0 0.0015244 0.0275912" },
        mass: { value: "0.73" },
        inertia: {
          ixx: "0.00278560230025",
          ixy: "0.0",
          ixz: "0.0",
          iyy: "0.000400033405336",
          iyz: "0.0",
          izz: "0.00256378041832",
        },
      },
      name: "panda_hand",
    },
  },
  "collisionBodyType-86896e24-85dd-44b3-8e34-b42b3b35978c": {
    id: "collisionBodyType-86896e24-85dd-44b3-8e34-b42b3b35978c",
    type: "collisionBodyType",
    dataType: "INSTANCE",
    properties: {
      componentShapes: [
        "collisionShapeType-590b0e9d-5cd2-4bdd-a457-8abc047c9a98",
      ],
      updateFields: ["componentShapes"],
      compileFn: 0,
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_hand-collisionbody",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  "collisionShapeType-3e45824d-0e23-492f-908e-2f5bb5036133": {
    id: "collisionShapeType-3e45824d-0e23-492f-908e-2f5bb5036133",
    type: "collisionShapeType",
    dataType: "INSTANCE",
    properties: {
      position: { x: 0, y: -0.012, z: 0.033 },
      rotation: { w: 1, x: 0, y: 0, z: 0 },
      scale: { x: 0.02, y: 0.025, z: 0.041 },
      keyword: "cube",
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      compileFn: 0,
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_rightfinger-cube-0",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  "meshType-06c4f9f5-b4e7-40f5-b510-db706e73bfa5": {
    id: "meshType-06c4f9f5-b4e7-40f5-b510-db706e73bfa5",
    type: "meshType",
    dataType: "INSTANCE",
    properties: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { w: 6.12323399573677e-17, x: 0, y: 0, z: 1 },
      scale: { x: 1, y: 1, z: 1 },
      keyword:
        "package://franka_ros/franka_description/meshes/visual/finger.dae",
      extraParams: null,
      compileFn: 0,
      updateFields: ["position", "rotation", "scale"],
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_rightfinger-mesh",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  panda_rightfinger: {
    id: "panda_rightfinger",
    type: "linkType",
    dataType: "INSTANCE",
    properties: {
      agent: "robotAgentType-3291d50f-9b47-4c7d-befb-dbc7a7311471",
      frameKey: "panda_rightfinger",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent", "frameKey"],
      position: { x: 0, y: -0.02, z: 0.0584 },
      rotation: { w: 1, x: 0, y: 0, z: 0 },
      relativeTo: "panda_hand",
      mesh: "meshType-06c4f9f5-b4e7-40f5-b510-db706e73bfa5",
      collision: "collisionBodyType-5e3607d1-fc75-46c6-992e-eb606abcc502",
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {
        "{}": {
          status: "PENDING",
          otherPropertyUpdates: {
            frame: "panda_hand",
            position: { x: 0, y: -0.02, z: 0.0584 },
            rotation: { w: 1, x: 0, y: 0, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
          },
        },
      },
      frame: "panda_hand",
      scale: { x: 1, y: 1, z: 1 },
    },
    name: "panda_rightfinger",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
    raw: {
      visual: [
        {
          origin: { rpy: "0 0 3.141592653589793", xyz: "0 0 0" },
          geometry: {
            mesh: {
              filename:
                "package://franka_ros/franka_description/meshes/visual/finger.dae",
            },
          },
        },
      ],
      collision: [
        {
          origin: { rpy: "0 0 0", xyz: "0.0 -0.012 0.033" },
          geometry: { box: { size: "0.02 0.025 0.041" } },
        },
      ],
      inertial: {
        origin: {
          rpy: "0 0 3.141592653589793",
          xyz: "0 -0.0145644 0.0227941",
        },
        mass: { value: "0.1" },
        inertia: {
          ixx: "3.01220925051e-05",
          ixy: "0.0",
          ixz: "0.0",
          iyy: "2.95873808038e-05",
          iyz: "0.0",
          izz: "6.95125211657e-06",
        },
      },
      name: "panda_rightfinger",
    },
  },
  "collisionBodyType-5e3607d1-fc75-46c6-992e-eb606abcc502": {
    id: "collisionBodyType-5e3607d1-fc75-46c6-992e-eb606abcc502",
    type: "collisionBodyType",
    dataType: "INSTANCE",
    properties: {
      componentShapes: [
        "collisionShapeType-3e45824d-0e23-492f-908e-2f5bb5036133",
      ],
      updateFields: ["componentShapes"],
      compileFn: 0,
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_rightfinger-collisionbody",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  "collisionShapeType-a0aa50d8-f1a5-4f4c-a9fe-b89f686fae10": {
    id: "collisionShapeType-a0aa50d8-f1a5-4f4c-a9fe-b89f686fae10",
    type: "collisionShapeType",
    dataType: "INSTANCE",
    properties: {
      position: { x: 0, y: 0.012, z: 0.033 },
      rotation: { w: 1, x: 0, y: 0, z: 0 },
      scale: { x: 0.02, y: 0.025, z: 0.041 },
      keyword: "cube",
      extraParams: null,
      updateFields: ["position", "rotation", "scale"],
      compileFn: 0,
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_leftfinger-cube-0",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  "meshType-430b6298-0366-4b8b-bdaf-80d7c6ff1670": {
    id: "meshType-430b6298-0366-4b8b-bdaf-80d7c6ff1670",
    type: "meshType",
    dataType: "INSTANCE",
    properties: {
      position: { x: 0, y: 0, z: 0 },
      rotation: { w: 1, x: 0, y: 0, z: 0 },
      scale: { x: 1, y: 1, z: 1 },
      keyword:
        "package://franka_ros/franka_description/meshes/visual/finger.dae",
      extraParams: null,
      compileFn: 0,
      updateFields: ["position", "rotation", "scale"],
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_leftfinger-mesh",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
  panda_leftfinger: {
    id: "panda_leftfinger",
    type: "linkType",
    dataType: "INSTANCE",
    properties: {
      agent: "robotAgentType-3291d50f-9b47-4c7d-befb-dbc7a7311471",
      frameKey: "panda_leftfinger",
      compileFn: 13,
      updateFields: ["position", "rotation", "relativeTo", "agent", "frameKey"],
      position: { x: 0, y: 0.02, z: 0.0584 },
      rotation: { w: 1, x: 0, y: 0, z: 0 },
      relativeTo: "panda_hand",
      mesh: "meshType-430b6298-0366-4b8b-bdaf-80d7c6ff1670",
      collision: "collisionBodyType-eab1a722-e317-4188-896f-4d1a55e45eae",
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {
        "{}": {
          status: "PENDING",
          otherPropertyUpdates: {
            frame: "panda_hand",
            position: { x: 0, y: 0.02, z: 0.0584 },
            rotation: { w: 1, x: 0, y: 0, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
          },
        },
      },
      frame: "panda_hand",
      scale: { x: 1, y: 1, z: 1 },
    },
    name: "panda_leftfinger",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
    raw: {
      visual: [
        {
          geometry: {
            mesh: {
              filename:
                "package://franka_ros/franka_description/meshes/visual/finger.dae",
            },
          },
        },
      ],
      collision: [
        {
          origin: { rpy: "0 0 0", xyz: "0.0 0.012 0.033" },
          geometry: { box: { size: "0.02 0.025 0.041" } },
        },
      ],
      inertial: {
        origin: { rpy: "0 0 0", xyz: "0 0.0145644 0.0227941" },
        mass: { value: "0.1" },
        inertia: {
          ixx: "3.01220925051e-05",
          ixy: "0.0",
          ixz: "0.0",
          iyy: "2.95873808038e-05",
          iyz: "0.0",
          izz: "6.95125211657e-06",
        },
      },
      name: "panda_leftfinger",
    },
  },
  "collisionBodyType-eab1a722-e317-4188-896f-4d1a55e45eae": {
    id: "collisionBodyType-eab1a722-e317-4188-896f-4d1a55e45eae",
    type: "collisionBodyType",
    dataType: "INSTANCE",
    properties: {
      componentShapes: [
        "collisionShapeType-a0aa50d8-f1a5-4f4c-a9fe-b89f686fae10",
      ],
      updateFields: ["componentShapes"],
      compileFn: 0,
      singleton: false,
      status: "PENDING",
      errorCode: null,
      compiled: {},
    },
    name: "panda_leftfinger-collisionbody",
    canDelete: true,
    canEdit: true,
    editing: false,
    selected: false,
  },
};
