[package]
name = "coframe-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
console_error_panic_hook = { version = "0.1.7" }
lively_tk = {git = "https://github.com/Wisc-HCI/lively_tk", rev="71434f88f2198fc287c02ee7d51df48a66eb88e4"}
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"]}

[profile.release]
opt-level = 3
codegen-units = 1

[profile.dev]
opt-level = 3
debug = true
codegen-units = 1