/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import UW from './UW.glb';

export default function Model(props) {

  const { nodes, materials } = useGLTF(UW);
  return [ {
    type:'group',
    scale: [3,3,3],
    position: [0,0,0],
    rotation: [0,0,Math.PI],
    children: [
      { type: 'raw', geometry: nodes.UW.geometry, material: materials.UW }
    ]}
  ]

}

useGLTF.preload(UW)
